---Q1. What is the revenue generated by Male vs Female?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender;


---Q2. Which customers used discount but still spent more than the average purchase amaount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) FROM customer);


---Q3. What are the top 5 products with highest average review rating?
SELECT item_purchased, AVG(review_rating) as "Average_review_rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) desc
LIMIT 5;


---Q4. Calculate the average purchase amounts between standard and epress shipping.
SELECT shipping_type, AVG(purchase_amount)
FROM customer
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type


---Q5. Do subscribed customers spend more? Compare average spend and total revenue amonst them.
SELECT subscription_status,
AVG(purchase_amount) as "Average_purchase_amount",
SUM(purchase_amount) as "Total_purchase_amount"
FROM customer
GROUP BY subscription_status

